server:
  port: 8189
  servlet:
    context-path: /api/v1/app
#  servlet:
#    session:
#      timeout: 60s



#spring:
#  datasource:
#
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 12345
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#
#
#  flyway:
#    url: jdbc:postgresql://localhost:5432/postgres
#
#    user: postgres
#    password: 12345
#
#    enabled: true
#    locations: classpath:db/migration

#



spring:
  datasource:
    sslmode: require
    url: jdbc:postgresql://ec2-44-206-89-185.compute-1.amazonaws.com:5432/df7bei5oqt8ouc
    username: wndobaytuzibvw
    password: 17bba88b52d94558cddbc8c061745e8c6e82e9be0e08ad922f5d19535329e52a
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect




  flyway:
    sslmode: required
    url: jdbc:postgresql://ec2-44-206-89-185.compute-1.amazonaws.com:5432/df7bei5oqt8ouc

    user: wndobaytuzibvw
    password: 17bba88b52d94558cddbc8c061745e8c6e82e9be0e08ad922f5d19535329e52a

    enabled: true
    locations: classpath:db/migration